# Generated by Django 5.0.6 on 2024-07-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_taskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Approved', 'Approved')], default='Pending', max_length=15),
        ),
    ]
